# Generated by Django 3.0.4 on 2021-07-02 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True, verbose_name='Nombre Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=14)),
                ('primer_nombre', models.CharField(max_length=35)),
                ('segundo_nombre', models.CharField(max_length=35)),
                ('apellido_paterno', models.CharField(max_length=35)),
                ('apellido_materno', models.CharField(max_length=35)),
                ('departamento', models.CharField(max_length=30)),
                ('contrato', models.CharField(choices=[('D', 'DETERMINADO'), ('I', 'INDETERMINADO')], default='D', max_length=1)),
                ('estado', models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Secciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('tipo_documento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Indexaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d')),
                ('cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Expedientes')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Documentos')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Secciones')),
            ],
        ),
        migrations.AddField(
            model_name='documentos',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RRHH.Secciones'),
        ),
    ]
