# Generated by Django 3.0.4 on 2021-05-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexaciones',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
