# Generated by Django 3.0.4 on 2021-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='estado',
            field=models.CharField(choices=[('O', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1),
        ),
    ]
