# Generated by Django 3.0.4 on 2021-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_auto_20210509_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d')),
            ],
        ),
    ]
