# Generated by Django 3.0.4 on 2021-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0003_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientes',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d'),
        ),
    ]
