# Generated by Django 3.0.4 on 2021-07-04 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RRHH', '0003_auto_20210704_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secciones',
            name='date_update',
        ),
        migrations.RemoveField(
            model_name='secciones',
            name='user_update',
        ),
        migrations.AddField(
            model_name='secciones',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='secciones',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_secciones_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='secciones',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rrhh_secciones_creation', to=settings.AUTH_USER_MODEL),
        ),
    ]
