# Generated by Django 3.0.4 on 2021-06-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0004_expedientes_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doc',
        ),
        migrations.AddField(
            model_name='documentos',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RRHH.Secciones'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Registros',
        ),
    ]
