# Generated by Django 3.0.4 on 2021-07-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0004_auto_20210704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secciones',
            name='nombre',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
