# Generated by Django 3.0.4 on 2021-07-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='secccion',
        ),
        migrations.AddField(
            model_name='user',
            name='documento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
